version: "3.8"

services:
  test_db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  test:
    build: .
    restart: always
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic
        --no-input && gunicorn -b 0.0.0.0:80 main.wsgi --reload"
    volumes:
      - .:/app
      - ./static:/static
    ports:
      - "80:80"
    depends_on:
      - test_db
      - es
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: es
    environment:
      - node.name=vibhuvi-node
      - discovery.type=single-node
      - cluster.name=vibhuvi-es-data-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/elasticsearch.yml
    # networks:
      # - elastic
    ports:
      - 9200:9200

volumes:
  postgres_data:
  data:

# networks:
#   elastic:
#     driver: bridge
  # db_afl_network:
  #   driver: bridge
